# Generated by Django 4.2.4 on 2023-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_remove_event_image_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/media', upload_to='event_images/'),
        ),
    ]
