# Generated by Django 4.2.4 on 2023-08-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
