# Generated by Django 4.2.4 on 2023-08-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_event_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mission_statement', models.TextField()),
                ('values', models.TextField()),
                ('image', models.ImageField(upload_to='about_us_images/')),
            ],
        ),
    ]
