# Generated by Django 4.2.4 on 2023-08-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
